# Generated by Django 5.2.8 on 2025-11-21 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='model name')),
                ('metric_type', models.CharField(max_length=50, verbose_name='metric type')),
                ('metric_value', models.FloatField(verbose_name='metric value')),
                ('test_data_size', models.IntegerField(blank=True, null=True, verbose_name='test data size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'verbose_name': 'AI Model Performance',
                'verbose_name_plural': 'AI Model Performances',
                'db_table': 'knowledge_aimodelperformance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='category')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'knowledge_faq',
                'ordering': ['-view_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('category', models.CharField(choices=[('loan', 'Loan Information'), ('insurance', 'Insurance Information'), ('general', 'General Information'), ('procedure', 'Procedures'), ('faq', 'Frequently Asked Questions'), ('policy', 'Policies'), ('compliance', 'Compliance')], max_length=50, verbose_name='category')),
                ('subcategory', models.CharField(blank=True, max_length=50, verbose_name='subcategory')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries',
                'db_table': 'knowledge_knowledgeentry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category', models.CharField(choices=[('loan', 'Loan Processing'), ('insurance', 'Insurance Processing'), ('general', 'General Chat'), ('greeting', 'Greeting'), ('closing', 'Closing'), ('error', 'Error Handling'), ('validation', 'Input Validation')], max_length=50, verbose_name='category')),
                ('prompt_type', models.CharField(choices=[('system', 'System Prompt'), ('user', 'User Prompt'), ('assistant', 'Assistant Prompt'), ('instruction', 'Instruction Prompt')], max_length=20, verbose_name='prompt type')),
                ('content', models.TextField(verbose_name='content')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('version', models.IntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'db_table': 'prompts_prompt',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('conversation', 'Conversation'), ('faq', 'FAQ'), ('document', 'Document'), ('intent', 'Intent Example'), ('entity', 'Entity Example')], max_length=20, verbose_name='data type')),
                ('input_text', models.TextField(verbose_name='input text')),
                ('expected_output', models.TextField(blank=True, verbose_name='expected output')),
                ('intent', models.CharField(blank=True, max_length=100, verbose_name='intent')),
                ('entities', models.JSONField(blank=True, default=dict, verbose_name='entities')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='confidence score')),
                ('is_used_for_training', models.BooleanField(default=False, verbose_name='used for training')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validated at')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Data',
                'verbose_name_plural': 'Training Data',
                'db_table': 'knowledge_trainingdata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='version')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('change_summary', models.TextField(verbose_name='change summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('knowledge_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgeentry')),
            ],
            options={
                'verbose_name': 'Knowledge Version',
                'verbose_name_plural': 'Knowledge Versions',
                'db_table': 'knowledge_knowledgeversion',
                'ordering': ['-version'],
                'unique_together': {('knowledge_entry', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='version')),
                ('content', models.TextField(verbose_name='content')),
                ('change_summary', models.TextField(verbose_name='change summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.prompt')),
            ],
            options={
                'verbose_name': 'Prompt Version',
                'verbose_name_plural': 'Prompt Versions',
                'db_table': 'prompts_promptversion',
                'ordering': ['-version'],
                'unique_together': {('prompt', 'version')},
            },
        ),
    ]
