# Generated by Django 5.2.8 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=0, verbose_name='message count')),
                ('user_message_count', models.IntegerField(default=0, verbose_name='user message count')),
                ('ai_message_count', models.IntegerField(default=0, verbose_name='AI message count')),
                ('avg_response_time', models.FloatField(blank=True, null=True, verbose_name='average response time (seconds)')),
                ('total_duration', models.IntegerField(blank=True, null=True, verbose_name='total duration (seconds)')),
                ('satisfaction_score', models.FloatField(blank=True, null=True, verbose_name='satisfaction score')),
                ('intent_accuracy', models.FloatField(blank=True, null=True, verbose_name='intent accuracy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Conversation Analytics',
                'verbose_name_plural': 'Conversation Analytics',
                'db_table': 'analytics_conversationanalytics',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='widget name')),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('metric', 'Metric Card'), ('table', 'Table'), ('graph', 'Graph'), ('progress', 'Progress Bar')], max_length=20, verbose_name='widget type')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='configuration')),
                ('data_source', models.CharField(max_length=100, verbose_name='data source')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='refresh interval (seconds)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'db_table': 'analytics_dashboardwidget',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='metric name')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='value')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20, verbose_name='period')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'db_table': 'analytics_metric',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_time', models.IntegerField(blank=True, null=True, verbose_name='processing time (seconds)')),
                ('completion_time', models.IntegerField(blank=True, null=True, verbose_name='completion time (seconds)')),
                ('documents_count', models.IntegerField(default=0, verbose_name='documents count')),
                ('conversation_turns', models.IntegerField(default=0, verbose_name='conversation turns')),
                ('automation_level', models.FloatField(blank=True, null=True, verbose_name='automation level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Order Analytics',
                'verbose_name_plural': 'Order Analytics',
                'db_table': 'analytics_orderanalytics',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='report name')),
                ('report_type', models.CharField(choices=[('user_activity', 'User Activity Report'), ('conversation', 'Conversation Report'), ('order', 'Order Report'), ('performance', 'Performance Report'), ('custom', 'Custom Report')], max_length=50, verbose_name='report type')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='report data')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='file path')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='file size')),
                ('is_ready', models.BooleanField(default=False, verbose_name='is ready')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'analytics_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='metric name')),
                ('metric_value', models.FloatField(verbose_name='metric value')),
                ('metric_unit', models.CharField(blank=True, max_length=20, verbose_name='metric unit')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'System Performance',
                'verbose_name_plural': 'System Performances',
                'db_table': 'analytics_systemperformance',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('chat_start', 'Chat Started'), ('chat_message', 'Chat Message'), ('voice_start', 'Voice Chat Started'), ('file_upload', 'File Upload'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated')], max_length=50, verbose_name='action')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='resource type')),
                ('resource_id', models.IntegerField(blank=True, null=True, verbose_name='resource ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='session ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'analytics_useractivity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('session_duration', models.IntegerField(blank=True, null=True, verbose_name='session duration (seconds)')),
                ('page_views', models.IntegerField(default=0, verbose_name='page views')),
                ('conversations_count', models.IntegerField(default=0, verbose_name='conversations count')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='messages sent')),
                ('orders_created', models.IntegerField(default=0, verbose_name='orders created')),
                ('files_uploaded', models.IntegerField(default=0, verbose_name='files uploaded')),
                ('unique_sessions', models.IntegerField(default=1, verbose_name='unique sessions')),
                ('bounce_rate', models.FloatField(blank=True, null=True, verbose_name='bounce rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'User Engagement',
                'verbose_name_plural': 'User Engagements',
                'db_table': 'analytics_userengagement',
                'ordering': ['-date'],
            },
        ),
    ]
